{% set name = "gmsh" %}
{% set version = "4.9.0" %}
{% set sha256 = "b8ef133c9b66ffe12df1747e72d4acf19f1eb1e9cd95eb0f577cbc4081d9bea3" %}

package:
  name: gmsh-packages
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-source.tgz
  url: https://gmsh.info/src/{{ name }}-{{ version }}-source.tgz
  sha256: {{ sha256 }}
  patches:
    - patches/occ_convert_signal.patch
    - patches/fltk_nominmax.patch
    - patches/disable_wmain.patch
    # - patches/fix_and.patch

build:
  number: 0

outputs:
  - name: gmsh
    build:
      skip: true  # [win and vc<14]
      ignore_run_exports:
        - fltk
    script: build_gmsh.sh  # [not win]
    script: bld_gmsh.bat  # [win]
    requirements:
      build:
        - cmake
        - make  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libselinux') }}        # [linux]
        - {{ cdt('libxcb') }}            # [linux]
        - {{ cdt('libxau') }}            # [linux]
        - {{ cdt('libxdamage') }}        # [linux]
        - {{ cdt('libxxf86vm') }}        # [linux]
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - python *

      host:
        - libblas
        - liblapack
        - gmp  # [not win]
        - occt
        - fltk
        - libpng
        - jpeg
        - libglu  # [linux]
        - zlib
        - xorg-libxfixes     # [linux]
        - xorg-libxext       # [linux]
        - xorg-libxrender    # [linux]
        - xorg-libx11        # [linux]
        - xorg-libxmu        # [linux]

      run:
        - gmp  # [not win]
        - occt
        - libpng
        - jpeg
        - zlib
        - libglu  # [linux]
        - xorg-libxfixes     # [linux]
        - xorg-libxext       # [linux]
        - xorg-libxrender    # [linux]
        - xorg-libx11        # [linux]
        - xorg-libxmu        # [linux]

    test:
      commands:
        - gmsh -help
        - test "$(gmsh --version 2>&1)" == "{{ version }}"   # [unix]

  - name: python-gmsh
    build:
      noarch: python
    script: install_python.sh  # [not win]
    script: install_python.bat  # [win]
    requirements:
      run:
        - {{ pin_subpackage("gmsh", max_pin="x.x.x") }}
        - numpy
        - python
    test:
      imports:
        - gmsh

about:
  home: http://geuz.org/gmsh/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: A three-dimensional finite element mesh generator with built-in pre- and post-processing facilities
  description: |
    Gmsh is a free 3D finite element grid generator with a build-in CAD
    engine and post-processor. Its design goal is to provide a fast, light
    and user-friendly meshing tool with parametric input and advanced
    visualization capabilities. Gmsh is built around four modules:
    geometry, mesh, solver and post-processing. The specification of any
    input to these modules is done either interactively using the graphical
    user interface or in ASCII text files using Gmsh's own scripting
    language.

extra:
  recipe-maintainers:
    - guyer
    - isuruf
    - xywei
    - looooo
