{% set name = "gmsh" %}
{% set version = "4.15.0" %}
{% set sha256 = "abb2632715bd7d0130ded7144fd6263635cd7dea883b8df61ba4da58ce6a1dfe" %}

package:
  name: gmsh-packages
  version: {{ version }}

source:
  url: https://gmsh.info/src/{{ name }}-{{ version }}-source.tgz
  sha256: {{ sha256 }}
  patches:
    - patches/fltk_nominmax.patch

build:
  number: 1

outputs:
  - name: gmsh
    script: build_gmsh.sh  # [not win]
    script: bld_gmsh.bat  # [win]
    requirements:
      build:
        - cmake
        - make  # [unix]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - {{ cdt('libselinux') }}        # [linux]
        - {{ cdt('libxcb') }}            # [linux]
        - {{ cdt('libxau') }}            # [linux]
        - {{ cdt('libxdamage') }}        # [linux]
        - {{ cdt('libxxf86vm') }}        # [linux]
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - python *

      host:
        - libblas
        - liblapack
        - gmp                # [not win]
        - occt
        - fltk
        - libpng
        - libjpeg-turbo
        - libglu             # [linux]
        - libgl              # [linux]
        - zlib
        - xorg-libxfixes     # [linux]
        - xorg-libxext       # [linux]
        - xorg-libxrender    # [linux]
        - xorg-libx11        # [linux]
        - xorg-libxmu        # [linux]
        - xorg-xorgproto     # [linux]
        - cairo
        - libgl-devel        # [linux]

      run:
        - gmp  # [not win]
        - {{ pin_compatible('occt', max_pin='x.x.x') }}
        - libpng
        - libjpeg-turbo
        - zlib
        - libglu             # [linux]
        - libgl              # [linux]
        - _openmp_mutex      # [linux]
        - xorg-libxfixes     # [linux]
        - xorg-libxext       # [linux]
        - xorg-libxrender    # [linux]
        - xorg-libx11        # [linux]
        - xorg-libxmu        # [linux]

    test:
      commands:
        - gmsh -help
        - test "$(gmsh --version 2>&1)" == "{{ version }}"   # [unix]

  - name: python-gmsh
    build:
      noarch: python
      skip: true  # [build_platform != target_platform or target_platform != "linux-64"]
    script: install_python.sh  # [unix]
    requirements:
      host:
        - python {{ python_min }}
      run:
        # cannot use `pin_subpackage("gmsh", exact=True)` in noarch
        - gmsh {{ version }} *_{{ PKG_BUILDNUM }}
        - numpy
        - python >={{ python_min }}
    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - gmsh

about:
  home: https://gmsh.info/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: A three-dimensional finite element mesh generator with built-in pre- and post-processing facilities
  description: |
    Gmsh is a free 3D finite element grid generator with a build-in CAD
    engine and post-processor. Its design goal is to provide a fast, light
    and user-friendly meshing tool with parametric input and advanced
    visualization capabilities. Gmsh is built around four modules:
    geometry, mesh, solver and post-processing. The specification of any
    input to these modules is done either interactively using the graphical
    user interface or in ASCII text files using Gmsh's own scripting
    language.
  dev_url: https://gitlab.onelab.info/gmsh/gmsh/
  doc_url: https://gmsh.info/doc/texinfo/gmsh.html

extra:
  recipe-maintainers:
    - oliviertremblaynoel
    - adrianinsaval
    - guyer
    - isuruf
    - looooo
    - maresb
    - matthiasdiener
    - xywei
